export enum RepositoriesName {
  SUMMONER = 'SUMMONER',
  SUMMONER_LEAGUE = 'SUMMONER_LEAGUE',
  MATCH = 'MATCH',
  MATCH_PARTICIPANTS = 'MATCH_PARTICIPANTS'
}

export enum DatabaseEnum {
  CONTEXT = 'CONTEXT_DATABASE'
}
